
#define RGB_DI_PIN D4
#define RGBLED_NUM 1
// #define RGBLIGHT_ANIMATIONS
// #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_ALTERNATING

#define SOLENOID_PIN D0
#define SOLENOID_ENABLE
#define SOLENOID_ACTIVE true
// #define SOLENOID_DEFAULT_DWELL 40
// #define SOLENOID_MIN_DWELL 20
// #define SOLENOID_DEFAULT_BUZZ 1